components_manager:
  coro_pool:
    initial_size: 100
    max_size: 1000
  task_processors:
    fs-task-processor:
      worker_threads: 2
      thread_name: fs-worker
    main-task-processor:
      worker_threads: 4
  default_task_processor: main-task-processor
  components:
    server:
      listener:
        port: 8080
        task_processor: main-task-processor

    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: "@stderr"
          level: info

    handler-ping:
      path: /ping
      method: GET
      task_processor: main-task-processor
    handler-create-user:
      path: /api/v1/users
      method: POST
      task_processor: main-task-processor

    handler-get-user:
      path: /api/v1/users
      method: GET
      task_processor: main-task-processor

    handler-login:
      path: /api/v1/auth/login
      method: POST
      task_processor: main-task-processor

    handler-create-hotel:
      path: /api/v1/hotels
      method: POST
      task_processor: main-task-processor

    handler-list-hotels:
      path: /api/v1/hotels
      method: GET
      task_processor: main-task-processor

    handler-create-booking:
      path: /api/v1/bookings
      method: POST
      task_processor: main-task-processor
      auth:
        types:
          - jwt

    handler-list-user-bookings:
      path: /api/v1/bookings
      method: GET
      task_processor: main-task-processor
      auth:
        types:
          - jwt

    handler-cancel-booking:
      path: /api/v1/bookings/{id}
      method: DELETE
      task_processor: main-task-processor
      auth:
        types:
          - jwt
